name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build the project (Next.js)
        run: npm run build

      - name: Deploy to Vercel (Next.js)
        run: npx vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
